---
## Overrides defaults for production cluster
deployment_mode: "cluster"
clickhouse_version: "26.4.2.10"
clickhouse_replicas: 2
kafka_replication_factor: 3
kafka_num_partitions: 3
kafka_heap_size: "2G"
